# Generated by Django 3.2.9 on 2024-06-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='delivery_info',
            new_name='image_link',
        ),
    ]
