# Generated by Django 3.2.9 on 2024-06-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_rename_delivery_info_product_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image_link',
            field=models.URLField(),
        ),
    ]
